#include <stdio.h>
#include <stdlib.h>
#include "lexer.h"

int main(int argc, char *argv[])
{
    // The command line argument requires the testcase file and an output file
    // Example: ./stage1exe testcase.txt parsetreeOutFile.txt
    if (argc < 3)
    {
        printf("Usage: ./stage1exe <testcase.txt> <parsetreeOutFile.txt>\n");
        return 1;
    }

    int option;
    do
    {
        printf("\n======================================================\n");
        printf("               Compiler Project Driver                \n");
        printf("======================================================\n");
        printf("0 : For exit\n");
        printf("1 : For removal of comments\n");
        printf("2 : For printing the token list generated by the lexer\n");
        printf("3 : For parsing and verifying syntactic correctness\n");
        printf("4 : For printing the total execution time\n");
        printf("\nEnter option: ");

        if (scanf("%d", &option) != 1)
        {
            printf("Invalid input. Exiting.\n");
            break;
        }

        switch (option)
        {
        case 0:
            printf("Exiting compiler...\n");
            break;

        case 1:
        {
            printf("\n--- Comment Free Code ---\n");
            // The driver is required to print the comment-free code to the console
            removeComments(argv[1], "cleanFile.txt");

            FILE *cleanFp = fopen("cleanFile.txt", "r");
            if (cleanFp)
            {
                char c;
                while ((c = fgetc(cleanFp)) != EOF)
                {
                    putchar(c);
                }
                fclose(cleanFp);
            }
            else
            {
                printf("Error opening temporary clean file.\n");
            }
            break;
        }

        case 2:
        {
            FILE *fp = fopen(argv[1], "r");
            if (fp == NULL)
            {
                printf("Error: Could not open file %s\n", argv[1]);
                break;
            }

            // Reset line number (global variable in lexer.c)
            // so we can run Option 2 multiple times accurately.
            lineNumber = 1;

            twinBuffer B = initBuffer(fp);
            tokenInfo tk;

            printf("\n--- Token List ---\n");
            do
            {
                tk = getNextToken(B);

                // We skip printing TK_ERROR tokens in the formatted list
                // because getNextToken already prints the specific error message to the console.
                if (tk->tokenType != TK_EOF && tk->tokenType != TK_ERROR)
                {
                    // Formatted printing to match lexemesandtokens_t1.txt and t2.txt
                    printf("Line no. %-4d\t Lexeme %-15s\t Token %s\n",
                           tk->lineNo, tk->lexeme, tokenStrings[tk->tokenType]);
                }

                // Free the token after printing to avoid memory leaks
                TokenType currentType = tk->tokenType;
                free(tk);

                if (currentType == TK_EOF)
                    break;

            } while (1);

            free(B);
            fclose(fp);
            break;
        }

        case 3:
            printf("\n[Notice] Option 3 (Parser) is not implemented yet. Only Lexical analyzer module developed.\n");
            break;

        case 4:
            printf("\n[Notice] Option 4 (Timer) relies on both Lexer and Parser. Check back later.\n");
            break;

        default:
            printf("\nInvalid option. Please try again.\n");
        }
    } while (option != 0);

    return 0;
}